### PR TITLE
Implement generation of from impls for CHOICE

### LINKED ISSUE #34: Generate From impls for CHOICE
The format I am working with uses CHOICE quite a bit and it would be nice to be able to go from the inner type to the container. Perhaps a From impl for this could be auto-generated? I would be happy to take a stab at it, if it is deemed acceptable.

### PR DESCRIPTION
**Pull request by shahn**
I took the opportunity to fix a couple of rustc warnings and did a cargo fmt run before I started, let me know if you do not want to take that and I'll remove it (the second commit merges cleanly on main without it). 

This closes #34.

### CODE REVIEW

**Review by 6d7a — COMMENTED** [review]
Wow, that was fast. Thank you for the PR, also for the formatting. One more edge case I was thinking of:
```
ChoiceType ::= CHOICE {
  number INTEGER,
  another INTEGER
}
```
Would this lead to conflicting`From` implementations?

**Comment by shahn** [comment]
You are right, this edge case is problematic. Thank you for catching it! I did not think of a type such as `ChoiceType`. I would suggest that for such cases, I simply remove duplicates and (silently) do not generate a From impl for any of the ambiguous variants. Alternatively, I could also silently not generate any From impls for such a type, but that does not really seem warranted if it isn't ambiguous. I cannot think of another solution right now, but of course am open if you have more ideas.

**Comment by 6d7a** [comment]
I'd say it should be fine if the compiler simply removes duplicates silently.

**Comment by shahn** [comment]
Made a trivial fix, happy to squash the last two commits if you prefer. Thanks for the super fast replies by the way!

**Review by 6d7a — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
